### ISSUE TITLE
"lncli queryroutes" crash

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/lnd#4]
Multi-hop payment is fine but every time when running `lncli queryroutes` will crash `lnd` immediately:

```
panic: runtime error: index out of range

goroutine 432 [running]:
main.(*rpcServer).QueryRoutes(0xc420311ad0, 0x11223e0, 0xc420285bf0, 0xc420765140, 0xc420311ad0, 0xc420285c60, 0xc4306a8ab0)
	/home/ubuntu/gocode/src/github.com/shelvenzhou/lnd/rpcserver.go:2627 +0x4d2
github.com/shelvenzhou/lnd/lnrpc._Lightning_QueryRoutes_Handler(0xf0bf60, 0xc420311ad0, 0x11223e0, 0xc420285bf0, 0xc420590f00, 0x0, 0x0, 0x0, 0x42c134, 0x10880b0)
	/home/ubuntu/gocode/src/github.com/shelvenzhou/lnd/lnrpc/rpc.pb.go:5430 +0x244
github.com/shelvenzhou/lnd/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc42051c640, 0x1127560, 0xc430664c00, 0xc42047c500, 0xc420311bf0, 0x163a530, 0xc420285c50, 0x0, 0x0)
	/home/ubuntu/gocode/src/github.com/shelvenzhou/lnd/vendor/google.golang.org/grpc/server.go:781 +0x9c8
github.com/shelvenzhou/lnd/vendor/google.golang.org/grpc.(*Server).handleStream(0xc42051c640, 0x1127560, 0xc430664c00, 0xc42047c500, 0xc420285c50)
	/home/ubuntu/gocode/src/github.com/shelvenzhou/lnd/vendor/google.golang.org/grpc/server.go:981 +0x1318
github.com/shelvenzhou/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4207be8f0, 0xc42051c640, 0x1127560, 0xc430664c00, 0xc42047c500)
	/home/ubuntu/gocode/src/github.com/shelvenzhou/lnd/vendor/google.golang.org/grpc/server.go:551 +0x9f
created by github.com/shelvenzhou/lnd/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/gocode/src/github.com/shelvenzhou/lnd/vendor/google.golang.org/grpc/server.go:549 +0xa1
```

**Comment by h4x3rotab** [comment]
This issue has been fixed in the pending alpha version.
